
exports_files([
    "ThePhilosophersStone.txt",
    "ThePhilosophersStoneStopWordsRemoved.txt",
    "ThePhilosophersStonePunctuationsRemoved.txt",
    "ThePhilosophersStonePunctuationsStopWordsRemoved.txt"
])
