load("@rules_python//python:defs.bzl", "py_library")
load("@liby//:requirements.bzl", "requirement")

package(default_visibility = ["//visibility:public"])


py_library(
    name="about",
    srcs=["about.py"],
    deps=[
        "//src/core"
    ]
)
