load("@rules_python//python:defs.bzl", "py_library")


package(default_visibility = ["//visibility:public"])


py_library(
    name="liby",
    srcs=[
        "__init__.py",
    ],
    deps=[
        "//src/liby/web:about"
    ]
)
