load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

#################### Skylib ####################

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

#################### Python ####################

http_archive(
    name = "rules_python",
    sha256 = "48a838a6e1983e4884b26812b2c748a35ad284fd339eb8e2a6f3adf95307fbcd",
    strip_prefix = "rules_python-0.16.2",
    url = "https://github.com/bazelbuild/rules_python/archive/refs/tags/0.16.2.tar.gz",
)


load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python3_8",
    # Available versions are listed in @rules_python//python:versions.bzl.
    # We recommend using the same version your team is already standardized on.
    python_version = "3.8",
)

load("@python3_8//:defs.bzl", "interpreter")

load("@rules_python//python:pip.bzl", "pip_parse")


pip_parse(
    name = "libx",
    requirements_lock = "//src/libx:requirements.txt",
    python_interpreter_target = interpreter
)
load("@libx//:requirements.bzl", "install_deps")
install_deps()



# Create a central repo that knows about the dependencies needed from
# requirements.txt.
pip_parse(
    name = "liby",
    requirements_lock = "//src/liby:requirements.txt",
    python_interpreter_target = interpreter,
)

# Load the starlark macro which will define your dependencies.
load("@liby//:requirements.bzl", "install_deps")

# Call it to define repos for your requirements.
install_deps()



# Create a central repo that knows about the dependencies needed from
# requirements.txt.
pip_parse(
    name = "core",
    requirements_lock = "//src/core:requirements.txt",
    python_interpreter_target = interpreter,
)

# Load the starlark macro which will define your dependencies.
load("@core//:requirements.bzl", "install_deps")

# Call it to define repos for your requirements.
install_deps()



# Create a central repo that knows about the dependencies needed from
# requirements.txt.
pip_parse(
    name = "cusb",
    requirements_lock = "//customers/cusb:requirements.txt",
    python_interpreter_target = interpreter,
)

# Load the starlark macro which will define your dependencies.
load("@cusb//:requirements.bzl", "install_deps")

# Call it to define repos for your requirements.
install_deps()


# Create a central repo that knows about the dependencies needed from
# requirements.txt.
pip_parse(
    name = "cusc",
    requirements_lock = "//customers/cusc:requirements.txt",
    python_interpreter_target = interpreter,
)

# Load the starlark macro which will define your dependencies.
load("@cusc//:requirements.bzl", "install_deps")

# Call it to define repos for your requirements.
install_deps()



