load("@rules_python//python:defs.bzl", "py_library")


package(default_visibility = ["//visibility:public"])



py_library(
    name="core",
    srcs=[
        "__init__.py",
    ],
    deps=[
        "//src/core/web:app",
        "//src/core/time"
    ]
)
