load("@io_bazel_rules_k8s//k8s:objects.bzl", "k8s_objects")


k8s_objects(
    name="apps",
    objects = [
        "//examples/apps/app_a/k8s:app_a",
        "//examples/apps/app_b/k8s:app_b"
    ]
)

