
py_test(
    name = "test_stop_words",
    srcs=["test_stop_words.py"],
    deps=["//src/preprocessing:stop_words"]
)

py_test(
    name = "test_punctuation",
    srcs=["test_punctuation.py"],
    deps=["//src/preprocessing:punctuation"]
)
