py_test(
    name = "test_filter",
    srcs=["test_filter.py"],
    deps=["//src/preprocessing/filter:filter"],
)

py_test(
    name = "test_filter_word",
    srcs=["test_filter_word.py"],
    deps=["//src/preprocessing/filter:filter"],
)

py_test(
    name = "test_stop_words",
    srcs=["test_stop_words.py"],
    deps=["//src/preprocessing:stop_words"]
)

py_test(
    name = "test_punctuation",
    srcs=["test_punctuation.py"],
    deps=["//src/preprocessing:punctuation"]
)
